### ISSUE TITLE
[FEAT]: Favicon for PaiNITTe 

### ISSUE THREAD

**Issue by Axhaat** [technical-council-nitt/painite-tc#47]
### Description

We are still using the default favicon of Docusaurus as PaiNITTe's favicon.

**Comment by ganeshvarbalaji** [comment]
### Suggestion
We can simply keep NIT-T Logo as the favicon, let's keep it simple. Or TeCOS logo.

I first of all can't understand why the name of the website is "PaiNITTe". Please explain.

**Comment by jaiakash** [comment]
@Axhaat thanks for the noticing the issue.

@ganeshvarbalaji instead of NITT logo,  we have dedicated PaiNITTe logo. Do you want to add it and send a PR?

**Comment by jaiakash** [comment]
> I first of all can't understand why the name of the website is "PaiNITTe". Please explain.

He He, PaiNITTe is website for all CTs, end sem papers. PaiNITTe = Pain + NITT :)

**Comment by ganeshvarbalaji** [comment]
Ha Ha, nicely thought name

> @ganeshvarbalaji instead of NITT logo, we have dedicated PaiNITTe logo. Do you want to add it and send a PR?

Yes, I'd like to do that

**Comment by jaiakash** [comment]
![image](https://user-images.githubusercontent.com/33419526/226627334-f4774736-b145-44ad-b944-73a4c2f0a4b8.png)

Sure this is the logo. Fork this repo and send PR with uodated logo.
