### ISSUE TITLE
design: logo and design of Painite website

### ISSUE THREAD

**Issue by jaiakash** [technical-council-nitt/painite-tc#7]

**Comment by tcnitt** [comment]
- [ ] https://www.canva.com/design/DAFGF3G827s/DDSyAGmwznRA6Q2uYi0dNA/edit?utm_content=DAFGF3G827s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
- [ ] https://www.canva.com/design/DAFGNKDuBtY/7LmvBjcIjr44l2_CgEoD0w/edit?utm_content=DAFGNKDuBtY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by tcnitt** [comment]
Color pallet (from NITT Logo)

#8e2e11
#baa290

**Comment by tcnitt** [comment]
![WhatsApp Image 2022-07-12 at 11 19 44 AM](https://user-images.githubusercontent.com/67335449/178535978-6d1701f2-3188-4d09-8b86-622b62f696fa.jpeg)

**Comment by Jaiharishan** [comment]
https://www.canva.com/design/DAFGNKDuBtY/7LmvBjcIjr44l2_CgEoD0w/edit

Both Color pallets attached.
